[package]
authors = ["Michele d'Amico <michele.damico@gmail.com>"]
categories = ["development-tools::testing"]
description = """
Reuse rstest attributes: create a set of tests and apply it 
to every scenario you want to test.
"""
edition = "2021"
homepage = "https://github.com/la10736/rstest"
keywords = ["test", "fixture"]
license = "MIT OR Apache-2.0"
name = "rstest_reuse"
readme = "README.md"
repository = "https://github.com/la10736/rstest"
rust-version = "1.61.0"
version = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
rand = "0.8.5"
syn = { version = "2.0.2", features = ["full", "extra-traits"] }

[dev-dependencies]
lazy_static = "1.4.0"
rstest_test = { path = "../rstest_test" }
temp_testdir = "0.2.3"
# To compile doc tests
rstest = { version = "0.22.0" }
